### PR TITLE
feat: add pwa in application

### PR DESCRIPTION
**Pull request by CarolAgueraAguiar**

### CODE REVIEW

**Comment by wesleynepo** [comment]
Did you check the Lighthouse output when testing locally? 
image

**Comment by CarolAgueraAguiar** [comment]
Locally mine works normally
image

**Comment by CarolAguera** [comment]
I adjusted the settings, and now it's working can you check ?

**Comment by CarolAgueraAguiar** [comment]
I adjusted the application could you check it please?

image

**Comment by wesleynepo** [comment]
The project will be discontinued, it's open source so you can deploy your fork.

**Pull request closed without merging**
